addpath('3rd-party', 'tests', 'tools')
mapMakerGUI;

fprintf([ ...
    'Welcome to the EKF SLAM MATLAB Simulator! \n' ...
    'To get started, either load one of the pre-made maps located in \n' ...
    'the root folder or build your own using waypoints, landmarks and \n' ...
    'obstacles. This software was developed by Jai Juneja \n' ...
    '(www.jaijuneja.com). If you would like to get in contact, email \n' ...
    ' jai.juneja@gmail.com. \n' ...
    ]);